#pragma once

#ifdef AUDIO_ENABLE
#    define STARTUP_SONG SONG(NO_SOUND)
#    define GOODBYE_SONG SONG(NO_SOUND)
#endif

//#define MIDI_BASIC
//#define MIDI_ADVANCED

#define ENCODER_RESOLUTION 4

#define ONYX_CONFIGURATOR

#define TAPPING_TERM 170
#define PERMISSIVE_HOLD
//#define RETRO_TAPPING
#define TAPPING_TOGGLE 2

//#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_ALPHAS_MODS
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CUSTOM_alphamap
#define RGB_MATRIX_STARTUP_HUE 43
#define RGB_MATRIX_STARTUP_SAT 255
#define RGB_MATRIX_STARTUP_VAL 255

#define UNICODE_SELECTED_MODES UC_LNX

#define PLANCK_EZ_USER_LEDS
